//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXFileExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXFileExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string ConsoleCaption {
            get {
                return ResourceManager.GetString("ConsoleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string Default_FileSystem_Copy_Continue {
            get {
                return ResourceManager.GetString("Default_FileSystem_Copy_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and Folders.
        /// </summary>
        internal static string Default_FileSystem_GroupText {
            get {
                return ResourceManager.GetString("Default_FileSystem_GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory.
        /// </summary>
        internal static string Default_FileSystem_GuiCallback_Directory {
            get {
                return ResourceManager.GetString("Default_FileSystem_GuiCallback_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string Default_FileSystem_GuiCallback_File {
            get {
                return ResourceManager.GetString("Default_FileSystem_GuiCallback_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Default_FileSystem_ItemCopyText {
            get {
                return ResourceManager.GetString("Default_FileSystem_ItemCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Default_FileSystem_ItemDeleteText {
            get {
                return ResourceManager.GetString("Default_FileSystem_ItemDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Folder.
        /// </summary>
        internal static string Default_FileSystem_ItemMakeFolderText {
            get {
                return ResourceManager.GetString("Default_FileSystem_ItemMakeFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Default_FileSystem_ItemMoveText {
            get {
                return ResourceManager.GetString("Default_FileSystem_ItemMoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Default_FileSystem_ItemRenameText {
            get {
                return ResourceManager.GetString("Default_FileSystem_ItemRenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Default_FileSystem_OperationName_Copy {
            get {
                return ResourceManager.GetString("Default_FileSystem_OperationName_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Default_FileSystem_OperationName_Move {
            get {
                return ResourceManager.GetString("Default_FileSystem_OperationName_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string Default_FileSystem_Sort_ByCreationDate {
            get {
                return ResourceManager.GetString("Default_FileSystem_Sort_ByCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Default_FileSystem_Sort_ByName {
            get {
                return ResourceManager.GetString("Default_FileSystem_Sort_ByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Default_FileSystem_Sort_Group {
            get {
                return ResourceManager.GetString("Default_FileSystem_Sort_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected dialog result..
        /// </summary>
        internal static string Default_FileSystem_UnexpectedDialogResult {
            get {
                return ResourceManager.GetString("Default_FileSystem_UnexpectedDialogResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file operation..
        /// </summary>
        internal static string Default_FileSystem_UnsupportedOperation {
            get {
                return ResourceManager.GetString("Default_FileSystem_UnsupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Default_Viewer_Command_Edit {
            get {
                return ResourceManager.GetString("Default_Viewer_Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Default_Viewer_Command_Save {
            get {
                return ResourceManager.GetString("Default_Viewer_Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Default_Viewer_Command_View {
            get {
                return ResourceManager.GetString("Default_Viewer_Command_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        internal static string Default_Viewer_GroupText {
            get {
                return ResourceManager.GetString("Default_Viewer_GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver.
        /// </summary>
        internal static string DefaultArchivatorGroupText {
            get {
                return ResourceManager.GetString("DefaultArchivatorGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string DefaultArchivatorItemCompress {
            get {
                return ResourceManager.GetString("DefaultArchivatorItemCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress.
        /// </summary>
        internal static string DefaultArchivatorItemDecompress {
            get {
                return ResourceManager.GetString("DefaultArchivatorItemDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0}.
        /// </summary>
        internal static string DefaultNetworkLocationName {
            get {
                return ResourceManager.GetString("DefaultNetworkLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network location with the name {0} already exists..
        /// </summary>
        internal static string DuplicateNetworkLocationName {
            get {
                return ResourceManager.GetString("DuplicateNetworkLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX File Explorer.
        /// </summary>
        internal static string DXFileExplorer {
            get {
                return ResourceManager.GetString("DXFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        internal static string NavigationPageShortcutsGroupText {
            get {
                return ResourceManager.GetString("NavigationPageShortcutsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string NavigationPageText {
            get {
                return ResourceManager.GetString("NavigationPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string NavPaneGroupCaptionDrives {
            get {
                return ResourceManager.GetString("NavPaneGroupCaptionDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string NavPaneGroupCaptionWindows {
            get {
                return ResourceManager.GetString("NavPaneGroupCaptionWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Locations.
        /// </summary>
        internal static string NetworkLocationsGroupText {
            get {
                return ResourceManager.GetString("NetworkLocationsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string NetworkLocationsItemAddText {
            get {
                return ResourceManager.GetString("NetworkLocationsItemAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Location.
        /// </summary>
        internal static string NetworkLocationsItemRemoveText {
            get {
                return ResourceManager.GetString("NetworkLocationsItemRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you about to delete the {0} {1}?.
        /// </summary>
        internal static string SureToDeleteMessage {
            get {
                return ResourceManager.GetString("SureToDeleteMessage", resourceCulture);
            }
        }
    }
}
